version: '3.7'

services:
  frontend:
    image: ghcr.io/geodis-tmoreau/container-mesh-mobile:main
    networks:
      - traefik
    labels:
      - traefik.enable=true
      - traefik.http.services.cm-mobile.loadbalancer.server.port=80
      - traefik.http.routers.cm-mobile.entrypoints=https
      - traefik.http.routers.cm-mobile.rule=Host(`cm-mobile.onerecord.fr`)

networks:
  traefik:
    external: true
    name: onerecord-traefik